# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
WORKDIR /build
COPY . .
RUN dotnet restore "order-service.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "order-service.dll"]

# Build Image
# docker build --rm -f dockerfile -t order-service .

# Run Image without env vars
# docker run -it --rm -p 5051:80 order-service

# Run Image with env vars
# docker run -it --rm -p 5051:80 order-service -e "App:UserSQLite=true" -e "App:ConnectionStrings:SQLServerConnection=<SQLSERVER_CONNECTION_STRING>"

# Browse using: 
# http://localhost:5051
# http://localhost:5051/food
# http://localhost:5051/config

# Publish Image to dockerhub
# docker tag order-service alexander-kastil/order-service
# docker push alexander-kastil/order-service