# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /app

COPY ["order-service/order-service.csproj", "order-service/"]
COPY ["food-app-common/food-app-common.csproj", "food-app-common/"] 

RUN dotnet restore "order-service/order-service.csproj"
COPY . .
WORKDIR "/app/order-service"

RUN dotnet build "order-service.csproj" -c Release -o /app/build
FROM build as publish
RUN dotnet publish "order-service.csproj" -c Release -o /app/publish

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "order-service.dll"]

# Build Image
# docker build --rm -f Dockerfile -t order-service .
# docker run -it --rm -p 5052:80 order-service

# docker tag order-service arambazamba/order-service
# docker push arambazamba/order-service

# Injecting environment variables into the container
# docker run -it --rm -p 5052:80 order-service -e "CosmosDB:AccountKey"="<AccountKey>"

# Browse using: 
# http://localhost:5054
