POST http://localhost:7071/api/process_payment
Content-Type: application/json

{
  "payment": {
    "amount": 100,
    "currency": "USD",
    "card": {
      "number": "4111111111111111",
      "expiry": "12/23",
      "cvv": "123"
    }
  }
}

### test container

POST http://localhost:5000/api/process_payment
Content-Type: application/json

{
  "payment": {
    "amount": 100,
    "currency": "USD",
    "card": {
      "number": "4111111111111111",
      "expiry": "12/23",
      "cvv": "123"
    }
  }
}