name: sk-build-docker-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/ai/sk-students-ai/*

trigger: none      
pr: none

variables:
  appPath: src/ai/sk-students-ai/
  imageName: students-ai
  acr: scACR

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Build"
    displayName: "Build StudentsAI Image"
    jobs:
      - job: "Build"
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: $(acr)
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(appPath)dockerfile'
              tags: 'latest'
          
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)